name : Scan for docker vulnerabilities

on:
  push:
    #branches: [main]
  workflow_dispatch:

jobs:
  Scan-Docker-vulnerabilities:

    runs-on : ubuntu-latest

    steps:

      - name : Check out
        uses: actions/checkout@v5
        
      - name: Scan Dockerfile
        uses: cr0hn/dockerfile-security@v0.2.0
        with:
          dockerfile: 'Dockerfile'
          output-file: 'security-results.json'
          fail-on-issues: false

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v5
        with: 
          name: security-df-results
          path: security-results.json

      - name: Set Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker container
        run: docker build -t sampleapp:latest .

      - name: Run the container
        run: docker run -d sampleapp:latest

      - name: Scan image using grype
        uses: anchore/scan-action@v6
        with:
          image: sampleapp:latest
          fail-build: false

      - name: Scan image using trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image: sampleapp:latest
