name : Scan for docker vulnerabilities

on:
  workflow_dispatch:

jobs:
  Scan-Docker-vulnerabilities:

    runs-on : ubuntu-latest

    steps:

      - name : Check out
        uses: actions/checkout@v5
        
      - name: Scan Dockerfile
        uses: cr0hn/dockerfile-security@v0.2.0
        with:
          dockerfile: 'Dockerfile'

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v5
        with: 
          name: security-df-results
          path: security-df-results.json

      - name: Set Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker container
        uses: docker/build-push-action@v4
        with:
          tags: localbuild/sampleapp:latest

      - name: Scan image using grype
        uses: anchore/scan-action@v6
        with:
          image: localbuild/sampleapp:latest

      - name: Scan image using trivy
        uses: LogixDevCo/trivy-scan-action@v1.0.0
        with:
          image: localbuild/sampleapp:latest