name : IaC-Check

on: 
  #push:
    #branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab  
  workflow_dispatch: 

jobs:
  check-iac-scanning:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Checkov Github actions
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: tf-aws/
          output_format: cli
        
      - name: Notify on success
        # This step will only run if all previous steps in this job succeeded
        if: ${{ success() }}
        run: echo "Workflow passed successfully."

      - name: Notify on failure
        # This step will only run if any previous step in this job failed
        if: ${{ failure() }}
        run: echo "Workflow failed with an error."
